server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/microservice
    username: postgres
    password: root
  cloud:
    config:
      allowOverride: true
      overrideNone: true
  application:
    name: HOTEL-SERVICE

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  config:
    import: optional:configserver:http://localhost:8085

#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    service-url:
#      defaultZone: http://localhost:8761/eureka

